name: flutter_libphonenumber_ios
description: iOS implementation of the flutter_libphonenumber plugin.
repository: https://github.com/bottlepay/flutter_libphonenumber/tree/main/packages/flutter_libphonenumber_ios
issue_tracker: https://github.com/bottlepay/flutter_libphonenumber/issues
version: 1.1.2

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: flutter_libphonenumber
    platforms:
      ios:
        pluginClass: FlutterLibphonenumberPlugin
        dartPluginClass: FlutterLibphonenumberIOS

dependencies:
  flutter:
    sdk: flutter
  flutter_libphonenumber_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
