name: flutter_libphonenumber
description: Leverages libphonenumber to allow for asynchronous and synchronous formatting of phone numbers in Flutter apps.
repository: https://github.com/bottlepay/flutter_libphonenumber/tree/main/packages/flutter_libphonenumber
issue_tracker: https://github.com/bottlepay/flutter_libphonenumber/issues
version: 2.5.1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_libphonenumber_android
      ios:
        default_package: flutter_libphonenumber_ios
      web:
        default_package: flutter_libphonenumber_web
      # linux:
      #   default_package: flutter_libphonenumber_linux
      # macos:
      #   default_package: flutter_libphonenumber_macos
      # windows:
      #   default_package: flutter_libphonenumber_windows

dependencies:
  flutter:
    sdk: flutter
  flutter_libphonenumber_android: ^1.4.1
  flutter_libphonenumber_ios: ^1.4.0
  flutter_libphonenumber_platform_interface: ^2.1.0
  flutter_libphonenumber_web: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
